# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(APP_SECRET)%"
    csrf_protection: true
    #serializer:      { enable_annotations: true }
    trusted_hosts:   ~
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_lifetime: 604800 # 1 week
        gc_divisor: 500 # Try to see if this reduces lock timeouts; see https://github.com/symfony/symfony/issues/20619
    fragments:       ~
    http_method_override: true
    php_errors:
        log: true
