parameters:
    user_group_icons:
        abusefilter: https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Advancedsettings.png/18px-Advancedsettings.png
        abusefilter-maintainer: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/AbuseFilterMaintainerIcon.png/18px-AbuseFilterMaintainerIcon.png
        bot: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Crystal_Clear_action_run.png/18px-Crystal_Clear_action_run.png
        botadmin: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Admin_bot.png/18px-Admin_bot.png
        bureaucrat: https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Human-preferences-desktop.svg/18px-Human-preferences-desktop.svg.png
        checkuser: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Gnome-searchtool.svg/18px-Gnome-searchtool.svg.png
        global-interface-editor: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Pliers_with_yellow_handles_(rotated).svg/18px-Pliers_with_yellow_handles_(rotated).svg.png
        global-renamer: https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Global_renamer-logo.svg/18px-Global_renamer-logo.svg.png
        global-sysop: https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Meta-Wiki_Global_sysop-2000px.png/18px-Meta-Wiki_Global_sysop-2000px.png
        interface-admin: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Pliers_with_yellow_handles_(rotated).svg/18px-Pliers_with_yellow_handles_(rotated).svg.png
        suppress: https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Crystal_Clear_action_run.png/18px-Crystal_Clear_action_run.png
        steward: https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Wikimedia_steward_Icon.svg/18px-Wikimedia_steward_Icon.svg.png
        sysop: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Mop.svg/18px-Mop.svg.png
